global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']  # Docker service name
    metrics_path: /metrics
    scheme: http  # Explicitly specify HTTP
